### PR TITLE
Worked on the basic look of the blog page. Imported Headlessui/React …

### PR DESCRIPTION
**Pull request by DanielMSantiago**
Decent amount going on here. Created basic layout of the blog page. Added a midsection that utilizes @headlessui/react to create the tabs and tab panels for a specific category and display blog post related to said category. Created a basic layout of what the blog post is gonna look like. Will most likely convert the blog post preview into a link so that when you click it, it brings you to a page with the full blog post. Created footer to house links to social media sites to connect to with their corresponding logo. 

BethlehemBlog2

https://github.com/TevvinStrong/bethlehembreadco/assets/85462034/9371f6e9-31ab-45b5-8594-67f07e8a138f

BethlehemBlog1

### CODE REVIEW

**Comment by TevvinStrong** [comment]
@DanielMSantiago This looks good, before we merge this PR can we center the blogs to the center of the page? If not I can handle this just let me know how you feel about implementing it. Should be just a css change.

**Comment by DanielMSantiago** [comment]
I agree. I also added after this merge, a hover effect that slowly enlarges the blog post. I will work on centering the blog posts and send in the next edits when done

**Comment by DanielMSantiago** [comment]
How do you feel about the social media on the footer? Should we keep it here on the blog page, or the about page?

**Comment by DanielMSantiago** [comment]
CenteredBlogs

Centered the blog posts. Added hover effect.

**Comment by DanielMSantiago** [comment]
https://github.com/TevvinStrong/bethlehembreadco/assets/85462034/578cfc7c-10cc-4053-ac46-d382bb6ddb3b

Hover effect

**Review by TevvinStrong — APPROVED** [review]

**Pull request merged**
